name: 🐍 GitHub Snake

on:
  schedule:
    - cron: '0 0 * * *'  # runs daily at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3

      - name: Run Snake
        uses: aloxaf/snake@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
