name: 🐍 GitHub Snake

on:
  schedule:
    - cron: '0 0 * * *'  # runs daily at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3

      - name: Generate GitHub Snake animation
        uses: jahirfiquitiva/github-snake-animation@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          since: '2021-01-01'
          speed: 50
          fps: 20
