name: 🐍 GitHub Snake

on:
  schedule:
    - cron: '0 0 * * *'  # runs daily at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3

      - name: Generate GitHub Snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-snake.svg
          gif_out_path: dist/github-snake.gif
          color_snake: green
          color_dots: '#c6e48b,#7bc96f,#239a3b,#196127'
